db: 
    driver: pdo_mysql
    name: php_examples
    host: localhost
    username: root
    password: root
    
package_manager:
    shipping_calculator: '\Bitwisdom\Deliveries\USShippingCalculator'
    
logging:
    file: logs/package_updates.log

other_key: other_value